name: pet_cam
description: turns your device into a petcam or baby monitor
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.1
  dart_mappable: ^4.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  socket_io_client: ^2.0.3+1

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
